<template>
  <div class="space-y-6">
    <h2 class="text-2xl font-bold text-gray-900">Usage Analytics</h2>

    <!-- Loading State -->
    <div v-if="loading" class="flex items-center justify-center py-12">
      <Loader2 class="w-8 h-8 animate-spin text-primary-600" />
    </div>

    <!-- Error State -->
    <div v-else-if="error" class="bg-red-50 border border-red-200 rounded-xl p-6 text-center">
      <p class="text-red-800 font-medium">{{ error }}</p>
      <button @click="fetchUsageStats()" class="mt-4 btn-primary">
        Retry
      </button>
    </div>

    <!-- Analytics Content -->
    <div v-else class="space-y-6">
      <!-- Daily Generations Chart -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <div class="flex items-center justify-between mb-4">
          <h3 class="text-lg font-semibold text-gray-900">Project Generations (Last 30 Days)</h3>
          <span class="text-sm text-gray-500">
            Total: {{ usage.daily_generations?.reduce((sum, d) => sum + d.count, 0) || 0 }} generations
          </span>
        </div>
        <div v-if="usage.daily_generations && usage.daily_generations.length > 0" class="space-y-2">
          <div v-for="day in usage.daily_generations" :key="day.date" class="flex items-center">
            <span class="text-sm text-gray-600 w-32">{{ new Date(day.date).toLocaleDateString() }}</span>
            <div class="flex-1 bg-gray-100 rounded-full h-6 relative overflow-hidden">
              <div
                class="bg-primary-500 h-full transition-all duration-500"
                :style="{ width: `${(day.count / maxDailyGenerations) * 100}%` }"
              ></div>
              <span class="absolute inset-0 flex items-center justify-end pr-2 text-xs font-medium text-gray-700">
                {{ day.count }}
              </span>
            </div>
          </div>
        </div>
        <div v-else class="text-center py-8">
          <p class="text-sm text-gray-500 mb-2">No generation data available</p>
          <p class="text-xs text-gray-400">Projects generated by students will appear here</p>
        </div>
      </div>

      <!-- Top Programs -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h3 class="text-lg font-semibold text-gray-900 mb-4">Top Programs by User Count</h3>
        <div v-if="usage.top_programs && usage.top_programs.length > 0" class="space-y-3">
          <div v-for="(prog, index) in usage.top_programs" :key="prog.program" class="flex items-center justify-between">
            <div class="flex items-center space-x-3">
              <span class="flex items-center justify-center w-8 h-8 rounded-full bg-primary-100 text-primary-600 font-semibold text-sm">
                {{ index + 1 }}
              </span>
              <span class="text-sm font-medium text-gray-900">{{ prog.program }}</span>
            </div>
            <span class="px-3 py-1 bg-gray-100 text-gray-800 rounded-full text-sm font-medium">
              {{ prog.count }} users
            </span>
          </div>
        </div>
        <p v-else class="text-sm text-gray-500">No program data available</p>
      </div>

      <!-- AI Provider Usage -->
      <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
        <h3 class="text-lg font-semibold text-gray-900 mb-4">AI Provider Usage</h3>
        <div v-if="usage.ai_provider_usage && usage.ai_provider_usage.length > 0" class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div
            v-for="provider in usage.ai_provider_usage"
            :key="provider.provider"
            class="bg-gray-50 rounded-lg p-4 text-center"
          >
            <p class="text-2xl font-bold text-gray-900">{{ provider.count }}</p>
            <p class="text-sm text-gray-600 uppercase mt-1">{{ provider.provider }}</p>
          </div>
        </div>
        <p v-else class="text-sm text-gray-500">No AI provider usage data available</p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { Loader2 } from 'lucide-vue-next'
import axios from 'axios'

const loading = ref(true)
const error = ref(null)
const usage = ref({
  daily_generations: [],
  top_programs: [],
  ai_provider_usage: []
})

const maxDailyGenerations = computed(() => {
  if (!usage.value.daily_generations || usage.value.daily_generations.length === 0) return 1
  return Math.max(...usage.value.daily_generations.map(d => d.count))
})

const fetchUsageStats = async () => {
  loading.value = true
  error.value = null
  try {
    const token = localStorage.getItem('auth_token')
    if (!token) {
      error.value = 'No authentication token found. Please log in again.'
      setTimeout(() => {
        window.location.href = '/'
      }, 2000)
      return
    }
    
    const response = await axios.get('http://127.0.0.1:5000/api/admin/stats/usage', {
      headers: { Authorization: `Bearer ${token}` }
    })
    console.log('Analytics data received:', response.data)
    usage.value = response.data
  } catch (err) {
    console.error('Error fetching usage stats:', err)
    if (err.response) {
      console.error('Response data:', err.response.data)
      console.error('Response status:', err.response.status)
      
      // Redirect to home on authentication/authorization errors
      if (err.response.status === 401 || err.response.status === 403 || err.response.status === 422) {
        error.value = err.response.data?.message || 'Session expired. Redirecting to home page...'
        setTimeout(() => {
          window.location.href = '/'
        }, 2000)
        return
      }
      
      error.value = err.response.data?.message || `Error: ${err.response.status} - Failed to load analytics`
    } else {
      error.value = 'Network error. Please check if the backend server is running.'
    }
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  fetchUsageStats()
})
</script>
