"""Add Google OAuth fields to User model

Revision ID: 727e4f4a74af
Revises: 7f14598b0f41
Create Date: 2025-12-04 15:02:03.820173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727e4f4a74af'
down_revision = '7f14598b0f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=False, server_default='email'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_google_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('auth_provider')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
