"""Add progress tracking tables

Revision ID: 7f14598b0f41
Revises: 8c186c55d8f1
Create Date: 2025-11-17 15:27:48.940256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f14598b0f41'
down_revision = '8c186c55d8f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_project_id', sa.Integer(), nullable=False),
    sa.Column('phase_name', sa.String(length=100), nullable=False),
    sa.Column('phase_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_duration_weeks', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('actual_completion_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['saved_project_id'], ['saved_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phase_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_order', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['project_phase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_tracking_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('expected_completion_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_completion_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_project', schema=None) as batch_op:
        batch_op.drop_column('actual_completion_date')
        batch_op.drop_column('expected_completion_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('progress_tracking_enabled')

    op.drop_table('phase_task')
    op.drop_table('project_phase')
    # ### end Alembic commands ###
