"""Add extended FYP database schema with projects, resources, and user tracking

Revision ID: 8c186c55d8f1
Revises: f078f9765983
Create Date: 2025-11-06 11:06:01.911863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '8c186c55d8f1'
down_revision = 'f078f9765983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=False),
    sa.Column('objectives', sa.JSON(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('expected_outcomes', sa.Text(), nullable=True),
    sa.Column('program_area', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('ai_provider', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_topic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_topic_program_area'), ['program_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_topic_title'), ['title'], unique=False)

    op.create_table('resource_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('generated_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('form_data_snapshot', sa.JSON(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=20), nullable=True),
    sa.Column('generation_session_id', sa.String(length=100), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_topic_id'], ['project_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_project_generation_session_id'), ['generation_session_id'], unique=False)

    op.create_table('global_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['resource_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_topic_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_topic_id'], ['project_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_topic_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('skill_level', sa.String(length=20), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_topic_id'], ['project_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_skill_skill_name'), ['skill_name'], unique=False)

    op.create_table('saved_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_topic_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('custom_title', sa.String(length=500), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_topic_id'], ['project_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_topic_id', name='unique_user_project_save')
    )
    op.create_table('student_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('program', sa.String(length=100), nullable=True),
    sa.Column('academic_year', sa.String(length=10), nullable=True),
    sa.Column('skills_text', sa.Text(), nullable=True),
    sa.Column('interests_text', sa.Text(), nullable=True),
    sa.Column('difficulty_preference', sa.String(length=20), nullable=True),
    sa.Column('duration_preference', sa.String(length=20), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('additional_requirements', sa.Text(), nullable=True),
    sa.Column('supervisor_name', sa.String(length=255), nullable=True),
    sa.Column('budget_range', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('project_topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_topic_id'], ['project_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activity_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activity_session_id'), ['session_id'], unique=False)
        batch_op.create_index('ix_user_activity_user_type_date', ['user_id', 'activity_type', 'created_at'], unique=False)

    op.create_table('user_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.String(length=20), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_name', name='unique_user_skill')
    )
    with op.batch_alter_table('user_skill', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_skill_skill_name'), ['skill_name'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('program', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('academic_year', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_student_id'))
        batch_op.drop_column('academic_year')
        batch_op.drop_column('program')
        batch_op.drop_column('student_id')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('user_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_skill_skill_name'))

    op.drop_table('user_skill')
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_index('ix_user_activity_user_type_date')
        batch_op.drop_index(batch_op.f('ix_user_activity_session_id'))
        batch_op.drop_index(batch_op.f('ix_user_activity_activity_type'))

    op.drop_table('user_activity')
    op.drop_table('student_profile')
    op.drop_table('saved_project')
    with op.batch_alter_table('project_skill', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_skill_skill_name'))

    op.drop_table('project_skill')
    op.drop_table('project_resource')
    op.drop_table('global_resource')
    with op.batch_alter_table('generated_project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_project_generation_session_id'))

    op.drop_table('generated_project')
    op.drop_table('resource_category')
    with op.batch_alter_table('project_topic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_topic_title'))
        batch_op.drop_index(batch_op.f('ix_project_topic_program_area'))

    op.drop_table('project_topic')
    # ### end Alembic commands ###
