"""Add profile completion fields to User model

Revision ID: 9826b652d71c
Revises: 76ea17f3c9b2
Create Date: 2025-12-21 12:09:56.069454

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9826b652d71c'
down_revision = '76ea17f3c9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('project_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expected_duration', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('expected_duration')
        batch_op.drop_column('project_preference')
        batch_op.drop_column('skills')
        batch_op.drop_column('interests')

    # ### end Alembic commands ###
