"""rename_student_id_to_university

Revision ID: 3cf4709947a4
Revises: e22817220e9f
Create Date: 2025-12-08 19:21:56.371728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf4709947a4'
down_revision = 'e22817220e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_student_id'))
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.VARCHAR(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_student_id'), ['student_id'], unique=False)
        batch_op.drop_column('university')

    # ### end Alembic commands ###
