"""add workspace activity table

Revision ID: 5f5611ceeffc
Revises: e24887ab4e6a
Create Date: 2025-12-22 20:39:09.931392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f5611ceeffc'
down_revision = 'e24887ab4e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_activity_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_activity_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_activity_created_at'))
        batch_op.drop_index(batch_op.f('ix_workspace_activity_activity_type'))

    op.drop_table('workspace_activity')
    # ### end Alembic commands ###
